marcosrivasr/pull-request-demo

app.js

FIX: nombre de colaborador correcto

---

app.js

Fix: Aprendiendo Pull Request

---

app.js

nombre de colaborador correcto

---

app.js

FIX: nombre de collaborador

---

app.js

Nuevo colaborador

---

app.js

Mi primer pull request Gracias por el tutorial y la oportunidad de colaborar.
Buen día a todos.

Add: Collaborador & primer Pull Request

---

app.js

agrego mi nombre y usuario en twitter

practico para hacer un pull request

---

app.js

Fix: nuevo nombre de colaborador

---

app.js

añadí mi nombre y mi twiter

---

app.js

Fix: Nombre de colaborador correcto lac

---

app.js

Agregando a Lester

---

app.js

Fix: Agregación de mi cuenta de colaborador

---

app.js

Prueba Fork & Pull Request para repositorio de marcosrivasr.

Agregado nuevo colaborador Dgj86

---

app.js

FIX: Prueba PR

---

app.js

Añado mi nombre en esta lista😃

---

app.js

Updated pull-requets-demo file

---

app.js

A través de pull request podemos interactuar como contribuidores a los proyectos de otras personas y en este caso utilizamos esta práctica para anotar nuestro nombre y cuenta de twitter como estudiantes de este tutorial.

ADD my name

---

app.js

Fix: number e de usuario en aprobación

---

app.js

Agregar mi cuenta de Twitter - Pull request example

---

app.js

Soy Amilcar Serrano @amilcarse y me aguegué como colaborador.

FIX: Agregué datos como colaborador

---

app.js

fix - name colaborador

---

app.js

Fix: Agregando datos
